ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: base64:QjBEd21UTXZ6Q1VQY2N1SUdqTS9CallpM1JSTHN5L1h3QWZleTJySlJuWC9XbUczaGVBVFhndkdFUy9kQXh5QkJ5Qll3SHZoczJFbVphL1RweElFPVdkazdmVEsyZVUtQ3UvQkZpSD84L08wVlItU3lGeVl0akQyUkNDamVyMDg=
    jwtExpirationMs: 14400000


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
