ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: B0DwmTMvzCUPccuIGjM/BjYi3RRLsy/XwAfey2rJRnX/WmG3heATXgvGES/dAxyBByBYwHvhs2EmZa/TpxIE=Wdk7fTK2eU-Cu/BFiH?8/O0VR-SyFyYtjD2RCCjer08
    jwtExpirationMs: 14400000


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
